from app.agent.text_to_sql.models import (
    HeatTreatmentSchemaPackage,
    SchemaColumn,
    SchemaTable,
)


class HeatTreatmentSchemaProvider:
    def load(self) -> HeatTreatmentSchemaPackage:
        return HeatTreatmentSchemaPackage(
            schema_version="heat-treatment-schema-v1",
            tables=[
                SchemaTable(
                    name="mes_heat_treatment_record",
                    description="热处理主记录表，一条记录代表一次热处理流转/批次记录。",
                    primary_key="id",
                    columns=[
                        SchemaColumn(name="id", description="主键", data_type="BIGINT"),
                        SchemaColumn(name="record_no", description="热处理记录业务编号", data_type="VARCHAR"),
                        SchemaColumn(name="status", description="热处理状态", data_type="VARCHAR"),
                        SchemaColumn(name="items_json", description="绑定产品/篮筐等明细 JSON", data_type="JSON"),
                        SchemaColumn(name="equipment_id", description="设备 ID", data_type="BIGINT"),
                        SchemaColumn(name="equipment_code", description="设备编码", data_type="VARCHAR"),
                        SchemaColumn(name="equipment_name", description="设备名称", data_type="VARCHAR"),
                        SchemaColumn(name="created_time", description="创建时间", data_type="DATETIME"),
                        SchemaColumn(name="started_time", description="开始时间", data_type="DATETIME"),
                        SchemaColumn(name="finished_time", description="完成时间", data_type="DATETIME"),
                        SchemaColumn(name="update_time", description="更新时间", data_type="DATETIME"),
                    ],
                ),
                SchemaTable(
                    name="mes_equipment",
                    description="设备台账表，只开放设备标识和状态字段。",
                    primary_key="equipment_id",
                    columns=[
                        SchemaColumn(name="equipment_id", description="设备主键", data_type="BIGINT"),
                        SchemaColumn(name="equipment_code", description="设备编码", data_type="VARCHAR"),
                        SchemaColumn(name="equipment_name", description="设备名称", data_type="VARCHAR"),
                        SchemaColumn(name="type_id", description="设备类型 ID", data_type="BIGINT"),
                        SchemaColumn(name="equipment_status", description="设备状态：0停用 1运行 2维修 3报废", data_type="CHAR"),
                        SchemaColumn(name="create_time", description="创建时间", data_type="DATETIME"),
                        SchemaColumn(name="update_time", description="更新时间", data_type="DATETIME"),
                    ],
                ),
                SchemaTable(
                    name="mes_heat_treatment_param_record",
                    description="热处理参数记录表，记录各阶段提交的参数明细。",
                    primary_key="param_record_id",
                    columns=[
                        SchemaColumn(name="param_record_id", description="参数记录主键", data_type="BIGINT"),
                        SchemaColumn(name="heat_treatment_record_id", description="热处理主记录 ID", data_type="BIGINT"),
                        SchemaColumn(name="submit_id", description="参数提交批次 ID", data_type="BIGINT"),
                        SchemaColumn(name="submit_no", description="参数提交批次号", data_type="VARCHAR"),
                        SchemaColumn(name="submit_time", description="参数提交时间", data_type="DATETIME"),
                        SchemaColumn(name="equipment_code", description="设备编码", data_type="VARCHAR"),
                        SchemaColumn(name="device_type", description="设备类型", data_type="VARCHAR"),
                        SchemaColumn(name="product_code", description="产品编码", data_type="VARCHAR"),
                        SchemaColumn(name="product_name", description="产品名称", data_type="VARCHAR"),
                        SchemaColumn(name="bind_code", description="绑定码/篮筐码", data_type="VARCHAR"),
                        SchemaColumn(name="stage_code", description="阶段编码", data_type="VARCHAR"),
                        SchemaColumn(name="stage_name", description="阶段名称", data_type="VARCHAR"),
                        SchemaColumn(name="param_code", description="参数编码", data_type="VARCHAR"),
                        SchemaColumn(name="param_name", description="参数名称", data_type="VARCHAR"),
                        SchemaColumn(name="unit", description="单位", data_type="VARCHAR"),
                        SchemaColumn(name="param_value", description="参数值", data_type="VARCHAR"),
                        SchemaColumn(name="changed_flag", description="是否修改历史值", data_type="TINYINT"),
                    ],
                ),
            ],
            relationships=[
                "mes_heat_treatment_record.equipment_id = mes_equipment.equipment_id",
                "mes_heat_treatment_record.equipment_code = mes_equipment.equipment_code 可作为设备关联兜底。",
                "mes_heat_treatment_param_record.heat_treatment_record_id = mes_heat_treatment_record.id",
            ],
            status_semantics={
                "CREATED": "已创建，尚未开始",
                "RUNNING": "处理中",
                "FINISHED": "已完成",
                "TRANSFERRED": "已转序",
                "ENDED": "已结束",
                "CANCELLED": "已作废，常规统计应排除",
            },
            business_rules=[
                "常规统计应排除 status = 'CANCELLED' 的热处理主记录。",
                "完成类问题优先使用 status IN ('FINISHED','TRANSFERRED','ENDED')，并要求 finished_time IS NOT NULL。",
                "本月按 created_time 或 finished_time 过滤时，优先遵循用户语义；完成批次统计使用 finished_time。",
                "处理时长使用 TIMESTAMPDIFF(MINUTE, started_time, finished_time)，并过滤 started_time 与 finished_time 均非空。",
                "当前 Schema 没有统一计划完成时间字段，不能臆造 planned_finish_time、plan_duration 等字段。",
                "items_json 仅可作为展示或明确 JSON 查询使用；第一版批次统计按热处理主记录行数统计。",
            ],
            allowed_columns={
                "mes_heat_treatment_record": [
                    "id",
                    "record_no",
                    "status",
                    "items_json",
                    "equipment_id",
                    "equipment_code",
                    "equipment_name",
                    "created_time",
                    "started_time",
                    "finished_time",
                    "update_time",
                ],
                "mes_equipment": [
                    "equipment_id",
                    "equipment_code",
                    "equipment_name",
                    "type_id",
                    "equipment_status",
                    "create_time",
                    "update_time",
                ],
                "mes_heat_treatment_param_record": [
                    "param_record_id",
                    "heat_treatment_record_id",
                    "submit_id",
                    "submit_no",
                    "submit_time",
                    "equipment_code",
                    "device_type",
                    "product_code",
                    "product_name",
                    "bind_code",
                    "stage_code",
                    "stage_name",
                    "param_code",
                    "param_name",
                    "unit",
                    "param_value",
                    "changed_flag",
                ],
            },
            forbidden_columns={
                "mes_heat_treatment_record": [
                    "created_by",
                    "started_by",
                    "finished_by",
                    "void_reason",
                    "remark",
                    "update_by",
                ],
                "mes_equipment": [
                    "responsible_person",
                    "contact_phone",
                    "serial_number",
                    "manufacturer_name",
                    "image_url",
                    "qr_code",
                    "remark",
                ],
                "mes_heat_treatment_param_record": [
                    "submit_by",
                    "submit_by_name",
                    "photo_ids",
                    "create_by",
                    "update_by",
                ],
            },
            examples=[
                "统计本月每台热处理设备完成了多少批次",
                "查询最近三个月各设备平均处理时长",
                "查询本周已完成热处理记录的记录号、设备和完成时间",
            ],
        )
